// 40 most used according to chatgpt
export const iso639_2Languages = {
  ara: "Arabic",
  ben: "Bengali",
  chi: "Chinese (Bibliographic)",
  zho: "Chinese (Terminology)",
  cze: "Czech (Bibliographic)",
  ces: "Czech (Terminology)",
  dan: "Danish",
  dut: "Dutch (Bibliographic)",
  nld: "Dutch (Terminology)",
  eng: "English",
  fin: "Finnish",
  fre: "French (Bibliographic)",
  fra: "French (Terminology)",
  ger: "German (Bibliographic)",
  deu: "German (Terminology)",
  gre: "Greek, Modern (1453-) (Bibliographic)",
  ell: "Greek, Modern (1453-) (Terminology)",
  heb: "Hebrew",
  hin: "Hindi",
  hun: "Hungarian",
  ice: "Icelandic (Bibliographic)",
  isl: "Icelandic (Terminology)",
  ita: "Italian",
  jpn: "Japanese",
  kor: "Korean",
  lat: "Latin",
  nor: "Norwegian",
  per: "Persian (Bibliographic)",
  fas: "Persian (Terminology)",
  pol: "Polish",
  por: "Portuguese",
  rum: "Romanian (Bibliographic)",
  ron: "Romanian (Terminology)",
  rus: "Russian",
  san: "Sanskrit",
  srp: "Serbian",
  slo: "Slovak (Bibliographic)",
  slk: "Slovak (Terminology)",
  slv: "Slovenian",
  spa: "Spanish",
  swe: "Swedish",
  tam: "Tamil",
  tel: "Telugu",
  tha: "Thai",
  tur: "Turkish",
  ukr: "Ukrainian",
  urd: "Urdu",
  vie: "Vietnamese",
  wel: "Welsh (Bibliographic)",
  cym: "Welsh (Terminology)",
  yid: "Yiddish",
};
